CREATE TABLE [dbo].[ZStat]
(
	[Z_ID] INT NOT NULL PRIMARY KEY IDENTITY, 
    [CriticalZ] FLOAT NOT NULL DEFAULT 0, 
	[ObservedZ] FLOAT NOT NULL DEFAULT 0,
    [Alpha] FLOAT NOT NULL DEFAULT 0.05, 
    [TwoTailed] BIT NOT NULL DEFAULT 0, 

)
