//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ZPRO.SQLEntityORM
{
    using System;
    using System.Collections.Generic;
    
    public partial class Assignment
    {
        public int AssignmentID { get; set; }
        public string CourseID { get; set; }
        public string Type { get; set; }
        public string Name { get; set; }
        public System.DateTime DueDate { get; set; }
        public string Description { get; set; }
    }
}
