//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ZPRO.SQLEntityORM
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class myzprodataEntities : DbContext
    {
        public myzprodataEntities()
            : base("name=myzprodataEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Assignment> Assignments { get; set; }
        public virtual DbSet<Observation> Observations { get; set; }
        public virtual DbSet<Sample> Samples { get; set; }
        public virtual DbSet<TStat> TStats { get; set; }
        public virtual DbSet<User> Users { get; set; }
        public virtual DbSet<ZStat> ZStats { get; set; }
    }
}
