//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ZPRO.SQLEntityORM
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sample
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Sample()
        {
            this.Observations = new HashSet<Observation>();
        }
    
        public int SampleID { get; set; }
        public Nullable<int> StatisticID { get; set; }
        public double SampleMean { get; set; }
        public double SampleStDev { get; set; }
        public int SampleSize { get; set; }
        public string StdErrorMean { get; set; }
        public double PopulationMean { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Observation> Observations { get; set; }
        public virtual TStat TStat { get; set; }
        public virtual ZStat ZStat { get; set; }
    }
}
