using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using ZPRO.Model;
using ZPRO.SQLEntityORM;

namespace ZPRO.SQLEntityORM
{
    public class UserORM
    {
        public void InsertUser(UserModel user)
        {
            // This 'User' class was generated by the Entity ORM.
            User u = new User();
            u.FirstName = user.FirstName;
            u.LastName = user.LastName;
            u.Email = user.Email;
            u.Password = user.Password;
        }
    }
}
