//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ZPRO.SQLEntityORM
{
    using System;
    using System.Collections.Generic;
    
    public partial class ZStat
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ZStat()
        {
            this.Samples = new HashSet<Sample>();
        }
    
        public int Z_ID { get; set; }
        public double CriticalZ { get; set; }
        public double ObservedZ { get; set; }
        public double Alpha { get; set; }
        public bool TwoTailed { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Sample> Samples { get; set; }
    }
}
